name: Deploy to GCP

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write' # Habilitar el token de OIDC

env:
  PROJECT_ID: luma-idp
  REGION: us-central1
  SERVICE_NAME: store-demo
  REPOSITORY_NAME: mfe-store-demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Authenticate to GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/$(gcloud projects describe luma-idp --format="value(projectNumber)")/locations/global/workloadIdentityPools/github-demo-pool/providers/github-demo-provider'
          service_account: 'github-actions-deployer@luma-idp.iam.gserviceaccount.com'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Show Cloud Run Service URL
        run: |
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --format="value(status.url)"